import 'models/post_on_feed_model.dart';import 'package:dotted_border/dotted_border.dart';import 'package:flutter/material.dart';import 'package:mdsumsul_s_application5/core/app_export.dart';import 'package:mdsumsul_s_application5/widgets/custom_drop_down.dart';import 'package:mdsumsul_s_application5/widgets/custom_elevated_button.dart';import 'package:mdsumsul_s_application5/widgets/custom_text_form_field.dart';import 'provider/post_on_feed_provider.dart';class PostOnFeedScreen extends StatefulWidget {const PostOnFeedScreen({Key? key}) : super(key: key);

@override PostOnFeedScreenState createState() =>  PostOnFeedScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => PostOnFeedProvider(), child: PostOnFeedScreen()); } 
 }
class PostOnFeedScreenState extends State<PostOnFeedScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: SingleChildScrollView(child: Column(children: [_buildRowWithTelevisionAndPost(context), Divider(), SizedBox(height: 33.v), Align(alignment: Alignment.centerLeft, child: Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 5.v), decoration: AppDecoration.fillGray5007.copyWith(borderRadius: BorderRadiusStyle.roundedBorder27), child: Row(mainAxisSize: MainAxisSize.min, children: [CustomElevatedButton(height: 41.v, width: 85.h, text: "lbl_photos".tr, buttonStyle: CustomButtonStyles.fillPrimaryTL20, buttonTextStyle: CustomTextStyles.labelLargeMulishGray20003), Padding(padding: EdgeInsets.fromLTRB(14.h, 11.v, 6.h, 11.v), child: Text("lbl_videos".tr, style: CustomTextStyles.labelLargeMulishGray500))]))), SizedBox(height: 25.v), _buildStackWithParagrafAndTwo(context), SizedBox(height: 17.v), Padding(padding: EdgeInsets.only(left: 28.h, right: 24.h), child: Selector<PostOnFeedProvider, TextEditingController?>(selector: (context, provider) => provider.whatsOnYourMindController, builder: (context, whatsOnYourMindController, child) {return CustomTextFormField(controller: whatsOnYourMindController, hintText: "msg_what_s_on_your_mind".tr, hintStyle: CustomTextStyles.titleSmallMulishBlack90001SemiBold, textInputAction: TextInputAction.done, maxLines: 14, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 20.v), borderDecoration: TextFormFieldStyleHelper.fillGray, fillColor: appTheme.gray5007);})), SizedBox(height: 27.v), _buildPostIn(context), SizedBox(height: 27.v)]))))); } 
/// Section Widget
Widget _buildRowWithTelevisionAndPost(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 25.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgClosePrimary, height: 45.adaptSize, width: 45.adaptSize, onTap: () {onTapImgClose(context);}), Spacer(flex: 53), Padding(padding: EdgeInsets.only(top: 12.v, bottom: 6.v), child: Text("lbl_new_post".tr, style: theme.textTheme.titleMedium)), Spacer(flex: 46), Container(height: 45.v, width: 72.h, margin: EdgeInsets.only(right: 5.h), decoration: AppDecoration.outlineBlueA, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgTelevisionPrimary, height: 45.v, width: 72.h, alignment: Alignment.center), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 12.v), child: Text("lbl_post".tr, style: CustomTextStyles.bodySmallOnPrimary_1)))]))])); } 
/// Section Widget
Widget _buildStackWithParagrafAndTwo(BuildContext context) { return SizedBox(height: 66.v, width: 323.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 81.h, top: 13.v), child: Text("lbl_photo1202460".tr, style: CustomTextStyles.labelLargeMulishBlack90001))), Align(alignment: Alignment.center, child: DottedBorder(color: appTheme.gray600.withOpacity(0.5), padding: EdgeInsets.only(left: 2.h, top: 2.v, right: 2.h, bottom: 2.v), strokeWidth: 2.h, radius: Radius.circular(4), borderType: BorderType.RRect, dashPattern: [10, 10], child: Container(padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 8.v), decoration: AppDecoration.outlineGray6001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Container(height: 46.v, width: 60.h, decoration: BoxDecoration(color: theme.colorScheme.primaryContainer, borderRadius: BorderRadius.circular(5.h))))))])); } 
/// Section Widget
Widget _buildPostIn(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 23.h, right: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(top: 9.v, bottom: 8.v), child: Text("lbl_post_in".tr, style: theme.textTheme.titleMedium)), Expanded(child: Padding(padding: EdgeInsets.only(left: 11.h), child: Selector<PostOnFeedProvider, PostOnFeedModel?>(selector: (context, provider) => provider.postOnFeedModelObj, builder: (context, postOnFeedModelObj, child) {return CustomDropDown(hintText: "lbl_my_profile".tr, items: postOnFeedModelObj?.dropdownItemList ?? [], onChanged: (value) {context.read<PostOnFeedProvider>().onSelected(value);});})))])); } 

/// Navigates to the previous screen.
onTapImgClose(BuildContext context) { NavigatorService.goBack(); } 
 }
