import 'models/comment_model.dart';import 'package:flutter/material.dart';import 'package:mdsumsul_s_application5/core/app_export.dart';import 'package:mdsumsul_s_application5/widgets/app_bar/appbar_leading_image.dart';import 'package:mdsumsul_s_application5/widgets/app_bar/appbar_title.dart';import 'package:mdsumsul_s_application5/widgets/app_bar/custom_app_bar.dart';import 'package:mdsumsul_s_application5/widgets/custom_elevated_button.dart';import 'package:mdsumsul_s_application5/widgets/custom_icon_button.dart';import 'provider/comment_provider.dart';class CommentScreen extends StatefulWidget {const CommentScreen({Key? key}) : super(key: key);

@override CommentScreenState createState() =>  CommentScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => CommentProvider(), child: CommentScreen()); } 
 }
class CommentScreenState extends State<CommentScreen> {@override void initState() { super.initState(); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(bottom: 5.v), child: Column(children: [Divider(), SizedBox(height: 29.v), _buildOnlineStatus(context), SizedBox(height: 26.v), Align(alignment: Alignment.centerLeft, child: Container(width: 307.h, margin: EdgeInsets.only(left: 25.h, right: 42.h), child: Text("msg_lorem_ipsum_dolor".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodySmall))), SizedBox(height: 28.v), Container(height: 271.v, width: 325.h, decoration: BoxDecoration(color: theme.colorScheme.primaryContainer, borderRadius: BorderRadius.circular(6.h))), SizedBox(height: 24.v), _buildSendRow(context), SizedBox(height: 16.v), Divider(color: appTheme.gray20004), SizedBox(height: 29.v), _buildFriendRow(context), SizedBox(height: 25.v), Align(alignment: Alignment.centerLeft, child: Container(width: 307.h, margin: EdgeInsets.only(left: 25.h, right: 42.h), child: Text("msg_lorem_ipsum_dolor".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodySmall))), SizedBox(height: 33.v), _buildSendRow1(context), SizedBox(height: 16.v), Divider(color: appTheme.gray20004), SizedBox(height: 29.v), _buildContrastRow(context), SizedBox(height: 25.v), Align(alignment: Alignment.centerLeft, child: Container(width: 307.h, margin: EdgeInsets.only(left: 25.h, right: 42.h), child: Text("msg_lorem_ipsum_dolor".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodySmall))), SizedBox(height: 33.v), _buildSendRow2(context), SizedBox(height: 16.v), Divider(color: appTheme.gray20004)])))), bottomNavigationBar: _buildSecondaryButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 96.v, leadingWidth: 70.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgClosePrimary, margin: EdgeInsets.only(left: 25.h, top: 26.v, bottom: 25.v), onTap: () {onTapClose(context);}), centerTitle: true, title: AppbarTitle(text: "lbl_comments".tr), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildOnlineStatus(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 25.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [_buildContrast(context), Padding(padding: EdgeInsets.only(left: 16.h, top: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_anne_southern".tr, style: theme.textTheme.titleSmall), SizedBox(height: 4.v), Text("msg_03_sept_at_04_21".tr, style: theme.textTheme.bodySmall)])), Spacer(), Padding(padding: EdgeInsets.only(top: 10.v, bottom: 6.v), child: _buildButtonAccept(context, followLabel: "lbl_follow".tr))])); } 
/// Section Widget
Widget _buildSendRow(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 25.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgSendOnerror, height: 15.v, width: 17.h), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_36".tr, style: CustomTextStyles.bodySmallGray90001)), Spacer(), CustomImageView(imagePath: ImageConstant.imgFavoriteOnerror, height: 16.v, width: 18.h), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_85".tr, style: CustomTextStyles.bodySmallGray90001)), CustomImageView(imagePath: ImageConstant.imgUserOnerror, height: 16.v, width: 17.h, margin: EdgeInsets.only(left: 23.h)), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_12".tr, style: CustomTextStyles.bodySmallGray90001))])); } 
/// Section Widget
Widget _buildFriendRow(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 25.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [_buildContrast(context), Padding(padding: EdgeInsets.only(left: 16.h, top: 6.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_osman_hutchings".tr, style: theme.textTheme.titleSmall), SizedBox(height: 2.v), Text("msg_03_sept_at_04_21".tr, style: theme.textTheme.bodySmall)])), Spacer(), CustomElevatedButton(width: 78.h, text: "lbl_friend".tr, margin: EdgeInsets.only(top: 10.v, bottom: 6.v), buttonStyle: CustomButtonStyles.fillPurpleTL17, buttonTextStyle: CustomTextStyles.labelLargePrimary)])); } 
/// Section Widget
Widget _buildSendRow1(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 25.h, right: 28.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgSendOnerror, height: 15.v, width: 17.h), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_14".tr, style: CustomTextStyles.bodySmallGray90001)), Spacer(), CustomImageView(imagePath: ImageConstant.imgFavoriteOnerror, height: 16.v, width: 18.h), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_42".tr, style: CustomTextStyles.bodySmallGray90001)), CustomImageView(imagePath: ImageConstant.imgUserOnerror, height: 16.v, width: 17.h, margin: EdgeInsets.only(left: 24.h)), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_6".tr, style: CustomTextStyles.bodySmallGray90001))])); } 
/// Section Widget
Widget _buildContrastRow(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 25.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, decoration: IconButtonStyleHelper.fillGray, child: CustomImageView(imagePath: ImageConstant.imgContrastGray1000150x50)), Padding(padding: EdgeInsets.only(left: 16.h, top: 6.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_charley_crawford".tr, style: theme.textTheme.titleSmall), SizedBox(height: 2.v), Text("msg_03_sept_at_04_21".tr, style: theme.textTheme.bodySmall)])), Spacer(), Padding(padding: EdgeInsets.only(top: 10.v, bottom: 6.v), child: _buildButtonAccept(context, followLabel: "lbl_follow".tr))])); } 
/// Section Widget
Widget _buildSendRow2(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 25.h, right: 21.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgSendOnerror, height: 15.v, width: 17.h), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_8".tr, style: CustomTextStyles.bodySmallGray90001)), Spacer(), CustomImageView(imagePath: ImageConstant.imgFavoriteOnerror, height: 16.v, width: 18.h), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_186".tr, style: CustomTextStyles.bodySmallGray90001)), CustomImageView(imagePath: ImageConstant.imgUserOnerror, height: 16.v, width: 17.h, margin: EdgeInsets.only(left: 19.h)), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_38".tr, style: CustomTextStyles.bodySmallGray90001))])); } 
/// Section Widget
Widget _buildSecondaryButton(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 111.h, right: 111.h, bottom: 22.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_load_more_comments".tr, style: theme.textTheme.bodySmall), CustomImageView(imagePath: ImageConstant.imgArrowDownGray50001, height: 6.v, width: 10.h, margin: EdgeInsets.only(left: 9.h, top: 5.v, bottom: 6.v))])); } 
/// Common widget
Widget _buildContrast(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 2.h), decoration: AppDecoration.fillGray20004.copyWith(borderRadius: BorderRadiusStyle.roundedBorder27), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.end, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 36.v), Container(height: 14.adaptSize, width: 14.adaptSize, decoration: AppDecoration.fillGreen.copyWith(borderRadius: BorderRadiusStyle.roundedBorder7), child: CustomImageView(imagePath: ImageConstant.imgContrastGray10001, height: 13.adaptSize, width: 13.adaptSize, alignment: Alignment.center))])); } 
/// Common widget
Widget _buildButtonAccept(BuildContext context, {required String followLabel, }) { return SizedBox(height: 34.v, width: 78.h, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.center, child: Container(height: 34.v, width: 78.h, decoration: AppDecoration.fillOnPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: CustomImageView(imagePath: ImageConstant.imgUpload, height: 33.v, width: 77.h, alignment: Alignment.center))), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 6.v), child: Text(followLabel, style: CustomTextStyles.labelLargePrimary.copyWith(color: theme.colorScheme.primary))))])); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
