import 'models/sign_up_one_model.dart';import 'package:flutter/material.dart';import 'package:mdsumsul_s_application5/core/app_export.dart';import 'package:mdsumsul_s_application5/widgets/custom_outlined_button.dart';import 'provider/sign_up_one_provider.dart';class SignUpOneScreen extends StatefulWidget {const SignUpOneScreen({Key? key}) : super(key: key);

@override SignUpOneScreenState createState() =>  SignUpOneScreenState();

static Widget builder(BuildContext context) { return ChangeNotifierProvider(create: (context) => SignUpOneProvider(), child: SignUpOneScreen()); } 
 }
class SignUpOneScreenState extends State<SignUpOneScreen> {@override void initState() { super.initState();Future.delayed(const Duration(milliseconds: 3000), (){
NavigatorService.popAndPushNamed(AppRoutes.signUpTwoScreen, );}); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [Align(alignment: Alignment.centerRight, child: SizedBox(height: 148.v, width: 243.h, child: Stack(alignment: Alignment.centerRight, children: [CustomImageView(imagePath: ImageConstant.imgLogoNw1, height: 109.v, width: 110.h, radius: BorderRadius.circular(54.h), alignment: Alignment.bottomLeft, margin: EdgeInsets.only(bottom: 14.v)), Opacity(opacity: 0.2, child: CustomImageView(imagePath: ImageConstant.imgUnion, height: 148.v, width: 198.h, alignment: Alignment.centerRight))]))), SizedBox(height: 12.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 136.h), child: Text("lbl_sign_up".tr, style: CustomTextStyles.headlineSmallInterGray90003))), SizedBox(height: 15.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 70.h), child: Row(children: [Text("msg_already_have_an".tr, style: CustomTextStyles.bodyMediumInterGray90003), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_sign_in".tr, style: CustomTextStyles.titleSmallInterPrimary))]))), SizedBox(height: 46.v), Text("msg_create_an_account".tr, style: CustomTextStyles.labelLargeInterGray90003SemiBold), SizedBox(height: 13.v), Container(width: 266.h, margin: EdgeInsets.only(left: 53.h, right: 54.h), child: Text("msg_we_are_lorem_ipsum".tr, maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodySmallInterGray70001.copyWith(height: 1.71))), SizedBox(height: 32.v), CustomOutlinedButton(height: 44.v, width: 138.h, text: "lbl_basic_user".tr), SizedBox(height: 22.v), CustomOutlinedButton(height: 44.v, width: 158.h, text: "msg_celebrities_vips".tr), SizedBox(height: 21.v), _buildGoogleStack(context)])))); } 
/// Section Widget
Widget _buildGoogleStack(BuildContext context) { return Align(alignment: Alignment.centerLeft, child: SizedBox(height: 237.v, width: 323.h, child: Stack(alignment: Alignment.topRight, children: [Align(alignment: Alignment.topRight, child: Container(margin: EdgeInsets.only(top: 65.v, right: 79.h), padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 12.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder7), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("lbl_church_page".tr, style: CustomTextStyles.labelLargeInterGray90003)]))), Align(alignment: Alignment.topRight, child: Container(margin: EdgeInsets.only(right: 66.h), padding: EdgeInsets.symmetric(horizontal: 21.h, vertical: 12.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder7), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("lbl_church_leader".tr, style: CustomTextStyles.labelLargeInterGray90003)]))), Align(alignment: Alignment.bottomRight, child: Container(margin: EdgeInsets.only(bottom: 45.v), padding: EdgeInsets.symmetric(horizontal: 89.h, vertical: 13.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder7), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 4.v), Text("lbl_jump_to_next".tr, style: CustomTextStyles.titleSmallInterOnPrimary)]))), Opacity(opacity: 0.2, child: CustomImageView(imagePath: ImageConstant.imgUnion197x217, height: 197.v, width: 217.h, alignment: Alignment.bottomLeft))]))); } 
 }
